# Generated by Django 4.2 on 2024-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_current_time_room_is_playing_room_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video_type',
            field=models.CharField(choices=[('upload', 'Uploaded Video'), ('youtube', 'YouTube Video')], default='upload', max_length=10),
        ),
    ]
