# Generated by Django 4.2.16 on 2024-11-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='video_type',
        ),
    ]
