# Generated by Django 4.2.16 on 2024-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_room_video_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_playing',
        ),
        migrations.AlterField(
            model_name='room',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
