# Generated by Django 4.2.16 on 2024-11-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_room_current_time_room_is_playing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_playing',
        ),
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
